# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fluentd", "1.11.2"
gem "fluent-plugin-s3"
gem "fluent-plugin-record-modifier"
