version: '3.7'
services:
  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    env_file:
      ./fluentd/fluentd.env
    ports:
      - "24224:24224"

  web:
    image: nginx
    depends_on:
      - fluentd
    ports:
      - "80:80"
    environment:
      # Don't output logs with status code 2XX to stdout
      FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-sub-second-precision: "true"
        tag: docker.nginx
        env: FLUENTD_STDOUT_FILTER_PATTERN
